import cv2
image=cv2.imread("phase1/new.jpeg")
cv2.imshow("Image",image)
flipped_horizontal=cv2.flip(image,1)
cv2.imshow("Flipped Horizontal Image",flipped_horizontal)
flipped_vertical=cv2.flip(image,0)
cv2.imshow("Flipped Vertical Image",flipped_vertical)
flipped_both=cv2.flip(image,-1)
cv2.imshow("Flipped Both Image",flipped_both)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.imwrite("phase2/flipped_horizontal.jpeg",flipped_horizontal)
cv2.imwrite("phase2/flipped_vertical.jpeg",flipped_vertical)
cv2.imwrite("phase2/flipped_both.jpeg",flipped_both)